-- =============================================================================
-- Donorly – Complete Database Schema (fresh install)
-- =============================================================================
-- This script creates the entire Donorly database from scratch.
-- Run against an empty PostgreSQL database owned by the application user.
--
-- Audit columns present on every table:
--   created_at  TIMESTAMPTZ  — when the row was first inserted
--   created_by  UUID         — user who created the row
--   modified_at TIMESTAMPTZ  — when the row was last updated
--   modified_by UUID         — user who last updated the row
--
-- Convention:
--   • All primary keys are UUID generated by gen_random_uuid().
--   • Every tenant-owned table carries organization_id.
--   • Status / type columns use VARCHAR CHECK constraints.
--   • Soft-deletes use deleted_at TIMESTAMPTZ (NULL = alive).
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- PHASE 0 — Platform, tenants, identity, RBAC
-- ============================================================

CREATE TABLE organizations (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    name            VARCHAR(200) NOT NULL,
    slug            VARCHAR(120) NOT NULL UNIQUE,
    vertical        VARCHAR(50)  NOT NULL DEFAULT 'nonprofit',
    status          VARCHAR(30)  NOT NULL DEFAULT 'trial'
                        CHECK (status IN ('trial','active','suspended','cancelled')),
    logo_url        TEXT,
    primary_color   VARCHAR(20),
    timezone        VARCHAR(80)  NOT NULL DEFAULT 'America/Chicago',
    deleted_at      TIMESTAMPTZ,
    -- audit
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      UUID,
    modified_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    modified_by     UUID
);

CREATE TABLE organization_settings (
    organization_id UUID         PRIMARY KEY REFERENCES organizations(id),
    receipt_prefix  VARCHAR(20),
    default_currency VARCHAR(3)  NOT NULL DEFAULT 'USD',
    ai_enabled      BOOLEAN      NOT NULL DEFAULT false,
    payment_enabled BOOLEAN      NOT NULL DEFAULT false,
    -- audit
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      UUID,
    modified_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    modified_by     UUID
);

CREATE TABLE users (
    id                   UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    email                VARCHAR(255) NOT NULL,
    full_name            VARCHAR(200) NOT NULL,
    phone                VARCHAR(30),
    password_hash        TEXT,
    status               VARCHAR(30)  NOT NULL DEFAULT 'active'
                             CHECK (status IN ('invited','active','disabled')),
    is_platform_admin    BOOLEAN      NOT NULL DEFAULT false,
    active_session_token VARCHAR(100),
    last_login_at        TIMESTAMPTZ,
    -- audit
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by           UUID,
    modified_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    modified_by          UUID
);
CREATE UNIQUE INDEX uq_users_email ON users (lower(email));

-- Self-referencing FK for created_by/modified_by added after table exists
ALTER TABLE organizations        ADD CONSTRAINT fk_orgs_created_by  FOREIGN KEY (created_by)  REFERENCES users(id);
ALTER TABLE organizations        ADD CONSTRAINT fk_orgs_modified_by FOREIGN KEY (modified_by) REFERENCES users(id);
ALTER TABLE organization_settings ADD CONSTRAINT fk_org_settings_created_by  FOREIGN KEY (created_by)  REFERENCES users(id);
ALTER TABLE organization_settings ADD CONSTRAINT fk_org_settings_modified_by FOREIGN KEY (modified_by) REFERENCES users(id);
ALTER TABLE users ADD CONSTRAINT fk_users_created_by  FOREIGN KEY (created_by)  REFERENCES users(id);
ALTER TABLE users ADD CONSTRAINT fk_users_modified_by FOREIGN KEY (modified_by) REFERENCES users(id);

CREATE TABLE roles (
    id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    code        VARCHAR(80)  NOT NULL UNIQUE,
    name        VARCHAR(120) NOT NULL,
    scope       VARCHAR(30)  NOT NULL DEFAULT 'organization'
                    CHECK (scope IN ('platform','organization')),
    is_system   BOOLEAN      NOT NULL DEFAULT true,
    -- audit
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  UUID         REFERENCES users(id),
    modified_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    modified_by UUID         REFERENCES users(id)
);

CREATE TABLE permissions (
    id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    code        VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(255),
    -- audit
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  UUID         REFERENCES users(id),
    modified_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    modified_by UUID         REFERENCES users(id)
);

CREATE TABLE role_permissions (
    role_id       UUID NOT NULL REFERENCES roles(id),
    permission_id UUID NOT NULL REFERENCES permissions(id),
    PRIMARY KEY (role_id, permission_id),
    -- audit
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by    UUID        REFERENCES users(id),
    modified_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by   UUID        REFERENCES users(id)
);

CREATE TABLE organization_memberships (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID        NOT NULL REFERENCES organizations(id),
    user_id         UUID        NOT NULL REFERENCES users(id),
    role_id         UUID        NOT NULL REFERENCES roles(id),
    status          VARCHAR(30) NOT NULL DEFAULT 'active'
                        CHECK (status IN ('invited','active','disabled')),
    UNIQUE (organization_id, user_id),
    -- audit
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      UUID        REFERENCES users(id),
    modified_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by     UUID        REFERENCES users(id)
);
CREATE INDEX idx_memberships_user ON organization_memberships (user_id);
CREATE INDEX idx_memberships_org  ON organization_memberships (organization_id);

CREATE TABLE invitations (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID         NOT NULL REFERENCES organizations(id),
    email           VARCHAR(255) NOT NULL,
    role_id         UUID         NOT NULL REFERENCES roles(id),
    token_hash      VARCHAR(255) NOT NULL UNIQUE,
    status          VARCHAR(30)  NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','accepted','revoked','expired')),
    expires_at      TIMESTAMPTZ  NOT NULL,
    accepted_at     TIMESTAMPTZ,
    -- audit
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      UUID         REFERENCES users(id),
    modified_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    modified_by     UUID         REFERENCES users(id)
);
CREATE INDEX idx_invitations_org ON invitations (organization_id);

-- ============================================================
-- PHASE 1 — Donors
-- ============================================================

CREATE TABLE donors (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID         NOT NULL REFERENCES organizations(id),
    full_name       VARCHAR(200) NOT NULL,
    email           VARCHAR(255),
    phone           VARCHAR(30),
    city            VARCHAR(120),
    donor_type      VARCHAR(30)  NOT NULL DEFAULT 'individual'
                        CHECK (donor_type IN ('individual','family','business','anonymous')),
    status          VARCHAR(30)  NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active','inactive','do_not_contact','merged')),
    lifetime_giving NUMERIC(14,2) NOT NULL DEFAULT 0,
    deleted_at      TIMESTAMPTZ,
    -- audit
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      UUID         REFERENCES users(id),
    modified_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    modified_by     UUID         REFERENCES users(id)
);
CREATE INDEX idx_donors_org_name   ON donors (organization_id, full_name);
CREATE UNIQUE INDEX uq_donors_org_email ON donors (organization_id, lower(email)) WHERE email IS NOT NULL;

CREATE TABLE donor_profiles (
    donor_id           UUID         PRIMARY KEY REFERENCES donors(id),
    organization_id    UUID         NOT NULL REFERENCES organizations(id),
    occupation         VARCHAR(200),
    employer           VARCHAR(200),
    preferred_language VARCHAR(50),
    preferred_channel  VARCHAR(30),
    notes_private      TEXT,
    -- audit
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by         UUID         REFERENCES users(id),
    modified_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    modified_by        UUID         REFERENCES users(id)
);

CREATE TABLE donor_tags (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID        NOT NULL REFERENCES organizations(id),
    name            VARCHAR(80) NOT NULL,
    color           VARCHAR(20),
    UNIQUE (organization_id, name),
    -- audit
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      UUID        REFERENCES users(id),
    modified_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by     UUID        REFERENCES users(id)
);

CREATE TABLE donor_tag_assignments (
    donor_id    UUID NOT NULL REFERENCES donors(id),
    tag_id      UUID NOT NULL REFERENCES donor_tags(id),
    PRIMARY KEY (donor_id, tag_id),
    -- audit
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by  UUID        REFERENCES users(id),
    modified_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by UUID        REFERENCES users(id)
);

CREATE TABLE donor_notes (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID        NOT NULL REFERENCES organizations(id),
    donor_id        UUID        NOT NULL REFERENCES donors(id),
    note_text       TEXT        NOT NULL,
    note_type       VARCHAR(40),
    visibility      VARCHAR(20) NOT NULL DEFAULT 'team'
                        CHECK (visibility IN ('private','team')),
    -- audit
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      UUID        REFERENCES users(id),
    modified_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by     UUID        REFERENCES users(id)
);
CREATE INDEX idx_donor_notes_donor ON donor_notes (donor_id);

-- ============================================================
-- PHASE 1 — Campaigns
-- ============================================================

CREATE TABLE campaigns (
    id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID          NOT NULL REFERENCES organizations(id),
    name            VARCHAR(200)  NOT NULL,
    slug            VARCHAR(120)  NOT NULL,
    campaign_type   VARCHAR(50)   NOT NULL DEFAULT 'general',
    goal_amount     NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (goal_amount >= 0),
    start_date      DATE,
    end_date        DATE,
    status          VARCHAR(30)   NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft','active','paused','completed','archived')),
    UNIQUE (organization_id, slug),
    -- audit
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by      UUID          REFERENCES users(id),
    modified_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    modified_by     UUID          REFERENCES users(id)
);
CREATE INDEX idx_campaigns_org ON campaigns (organization_id);

CREATE TABLE campaign_milestones (
    id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID          NOT NULL REFERENCES organizations(id),
    campaign_id     UUID          NOT NULL REFERENCES campaigns(id),
    title           VARCHAR(200)  NOT NULL,
    target_amount   NUMERIC(14,2) NOT NULL DEFAULT 0,
    target_date     DATE,
    status          VARCHAR(30)   NOT NULL DEFAULT 'pending',
    -- audit
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by      UUID          REFERENCES users(id),
    modified_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    modified_by     UUID          REFERENCES users(id)
);

-- ============================================================
-- PHASE 1 — Pledges, pledge cards, follow-ups
-- ============================================================

CREATE TABLE pledges (
    id               UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id  UUID          NOT NULL REFERENCES organizations(id),
    campaign_id      UUID          NOT NULL REFERENCES campaigns(id),
    donor_id         UUID          NOT NULL REFERENCES donors(id),
    amount           NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    collected_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    frequency        VARCHAR(30)   NOT NULL DEFAULT 'one_time'
                         CHECK (frequency IN ('one_time','weekly','monthly','quarterly','yearly')),
    payment_method   VARCHAR(50),
    start_date       DATE,
    end_date         DATE,
    status           VARCHAR(30)   NOT NULL DEFAULT 'pending'
                         CHECK (status IN ('pending','active','fulfilled','cancelled','defaulted')),
    source           VARCHAR(50),
    notes            TEXT,
    -- audit
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by       UUID          REFERENCES users(id),
    modified_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    modified_by      UUID          REFERENCES users(id)
);
CREATE INDEX idx_pledges_org_campaign ON pledges (organization_id, campaign_id);
CREATE INDEX idx_pledges_org_donor    ON pledges (organization_id, donor_id);

CREATE TABLE pledge_schedules (
    id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID          NOT NULL REFERENCES organizations(id),
    pledge_id       UUID          NOT NULL REFERENCES pledges(id),
    due_date        DATE          NOT NULL,
    amount_due      NUMERIC(14,2) NOT NULL CHECK (amount_due > 0),
    status          VARCHAR(30)   NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','paid','overdue','cancelled')),
    -- audit
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by      UUID          REFERENCES users(id),
    modified_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    modified_by     UUID          REFERENCES users(id)
);
CREATE INDEX idx_pledge_schedules_pledge ON pledge_schedules (pledge_id);

CREATE TABLE pledge_cards (
    id                  UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id     UUID          NOT NULL REFERENCES organizations(id),
    campaign_id         UUID          REFERENCES campaigns(id),
    donor_id            UUID          REFERENCES donors(id),
    image_url           TEXT,
    extracted_json      JSONB,
    amount              NUMERIC(14,2),
    payment_method      VARCHAR(50),
    notes               TEXT,
    verification_status VARCHAR(30)   NOT NULL DEFAULT 'pending'
                            CHECK (verification_status IN ('pending','reviewed','approved','rejected')),
    -- audit
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by          UUID          REFERENCES users(id),
    modified_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    modified_by         UUID          REFERENCES users(id)
);
CREATE INDEX idx_pledge_cards_org ON pledge_cards (organization_id);

CREATE TABLE donor_assignments (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id  UUID        NOT NULL REFERENCES organizations(id),
    donor_id         UUID        NOT NULL REFERENCES donors(id),
    ambassador_user_id UUID      NOT NULL REFERENCES users(id),
    campaign_id      UUID        REFERENCES campaigns(id),
    status           VARCHAR(30) NOT NULL DEFAULT 'active'
                         CHECK (status IN ('active','completed','released')),
    UNIQUE (donor_id, campaign_id, ambassador_user_id),
    -- audit
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by       UUID        REFERENCES users(id),
    modified_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by      UUID        REFERENCES users(id)
);
CREATE INDEX idx_donor_assignments_ambassador ON donor_assignments (organization_id, ambassador_user_id);

CREATE TABLE follow_ups (
    id                 UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id    UUID        NOT NULL REFERENCES organizations(id),
    donor_id           UUID        NOT NULL REFERENCES donors(id),
    campaign_id        UUID        REFERENCES campaigns(id),
    assigned_to_user_id UUID       REFERENCES users(id),
    due_at             TIMESTAMPTZ,
    status             VARCHAR(30) NOT NULL DEFAULT 'open'
                           CHECK (status IN ('open','completed','cancelled','overdue')),
    outcome            VARCHAR(40),
    notes              TEXT,
    -- audit
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by         UUID        REFERENCES users(id),
    modified_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by        UUID        REFERENCES users(id)
);
CREATE INDEX idx_follow_ups_org_status ON follow_ups (organization_id, status);
CREATE INDEX idx_follow_ups_assignee   ON follow_ups (assigned_to_user_id);

-- ============================================================
-- PHASE 3 — Finance (payments & receipts)
-- ============================================================

CREATE TABLE payments (
    id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID          NOT NULL REFERENCES organizations(id),
    pledge_id       UUID          NOT NULL REFERENCES pledges(id),
    donor_id        UUID          NOT NULL REFERENCES donors(id),
    amount          NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    payment_method  VARCHAR(50),
    payment_date    DATE          NOT NULL DEFAULT CURRENT_DATE,
    reference       VARCHAR(200),
    notes           TEXT,
    recorded_by     UUID          REFERENCES users(id),
    -- audit
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by      UUID          REFERENCES users(id),
    modified_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    modified_by     UUID          REFERENCES users(id)
);
CREATE INDEX idx_payments_org    ON payments (organization_id, created_at DESC);
CREATE INDEX idx_payments_pledge ON payments (pledge_id);
CREATE INDEX idx_payments_donor  ON payments (organization_id, donor_id);

CREATE TABLE receipts (
    id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID          NOT NULL REFERENCES organizations(id),
    payment_id      UUID          NOT NULL REFERENCES payments(id),
    receipt_number  VARCHAR(50)   NOT NULL,
    issued_to       VARCHAR(200)  NOT NULL,
    amount          NUMERIC(14,2) NOT NULL,
    issued_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    issued_by       UUID          REFERENCES users(id),
    UNIQUE (organization_id, receipt_number),
    -- audit
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by      UUID          REFERENCES users(id),
    modified_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    modified_by     UUID          REFERENCES users(id)
);
CREATE INDEX idx_receipts_org ON receipts (organization_id, issued_at DESC);

-- ============================================================
-- PHASE 4 — Events & Volunteers
-- ============================================================

CREATE TABLE events (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID         NOT NULL REFERENCES organizations(id),
    campaign_id     UUID         REFERENCES campaigns(id),
    name            VARCHAR(200) NOT NULL,
    description     TEXT,
    event_type      VARCHAR(50)  NOT NULL DEFAULT 'general',
    location        VARCHAR(300),
    starts_at       TIMESTAMPTZ,
    ends_at         TIMESTAMPTZ,
    capacity        INTEGER,
    status          VARCHAR(30)  NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft','published','in_progress','completed','cancelled')),
    -- audit
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      UUID         REFERENCES users(id),
    modified_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    modified_by     UUID         REFERENCES users(id)
);
CREATE INDEX idx_events_org        ON events (organization_id);
CREATE INDEX idx_events_org_starts ON events (organization_id, starts_at);

CREATE TABLE event_registrations (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID         NOT NULL REFERENCES organizations(id),
    event_id        UUID         NOT NULL REFERENCES events(id),
    donor_id        UUID         REFERENCES donors(id),
    guest_name      VARCHAR(200) NOT NULL,
    guest_email     VARCHAR(255),
    guest_phone     VARCHAR(30),
    party_size      INTEGER      NOT NULL DEFAULT 1 CHECK (party_size > 0),
    status          VARCHAR(30)  NOT NULL DEFAULT 'registered'
                        CHECK (status IN ('registered','checked_in','cancelled','no_show')),
    check_in_code   VARCHAR(40)  NOT NULL,
    checked_in_at   TIMESTAMPTZ,
    checked_in_by   UUID         REFERENCES users(id),
    notes           TEXT,
    -- audit
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      UUID         REFERENCES users(id),
    modified_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    modified_by     UUID         REFERENCES users(id)
);
CREATE INDEX idx_event_registrations_event ON event_registrations (event_id);
CREATE INDEX idx_event_registrations_org   ON event_registrations (organization_id);
CREATE UNIQUE INDEX uq_event_registrations_code ON event_registrations (event_id, check_in_code);

CREATE TABLE volunteer_shifts (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID        NOT NULL REFERENCES organizations(id),
    event_id        UUID        NOT NULL REFERENCES events(id),
    title           VARCHAR(200) NOT NULL,
    description     TEXT,
    starts_at       TIMESTAMPTZ,
    ends_at         TIMESTAMPTZ,
    slots           INTEGER     NOT NULL DEFAULT 1 CHECK (slots > 0),
    status          VARCHAR(30) NOT NULL DEFAULT 'open'
                        CHECK (status IN ('open','full','closed','cancelled')),
    -- audit
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      UUID        REFERENCES users(id),
    modified_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by     UUID        REFERENCES users(id)
);
CREATE INDEX idx_volunteer_shifts_event ON volunteer_shifts (event_id);
CREATE INDEX idx_volunteer_shifts_org   ON volunteer_shifts (organization_id);

CREATE TABLE volunteer_assignments (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID        NOT NULL REFERENCES organizations(id),
    shift_id        UUID        NOT NULL REFERENCES volunteer_shifts(id),
    user_id         UUID        NOT NULL REFERENCES users(id),
    status          VARCHAR(30) NOT NULL DEFAULT 'assigned'
                        CHECK (status IN ('assigned','confirmed','checked_in','completed','cancelled')),
    checked_in_at   TIMESTAMPTZ,
    UNIQUE (shift_id, user_id),
    -- audit
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      UUID        REFERENCES users(id),
    modified_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by     UUID        REFERENCES users(id)
);
CREATE INDEX idx_volunteer_assignments_shift ON volunteer_assignments (shift_id);
CREATE INDEX idx_volunteer_assignments_user  ON volunteer_assignments (organization_id, user_id);

-- ============================================================
-- Townhalls
-- ============================================================

CREATE TABLE townhalls (
    id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id  UUID         NOT NULL REFERENCES organizations(id),
    person_name      VARCHAR(200) NOT NULL,
    address          VARCHAR(300),
    event_date       DATE,
    event_time       TIME,
    duration_minutes INTEGER      CHECK (duration_minutes IS NULL OR duration_minutes > 0),
    notes            TEXT,
    -- audit
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by       UUID         REFERENCES users(id),
    modified_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    modified_by      UUID         REFERENCES users(id)
);
CREATE INDEX idx_townhalls_org      ON townhalls (organization_id);
CREATE INDEX idx_townhalls_org_date ON townhalls (organization_id, event_date);

-- ============================================================
-- PHASE 5 — Communications
-- ============================================================

CREATE TABLE message_templates (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID         NOT NULL REFERENCES organizations(id),
    name            VARCHAR(200) NOT NULL,
    channel         VARCHAR(20)  NOT NULL DEFAULT 'email'
                        CHECK (channel IN ('email','sms')),
    subject         VARCHAR(300),
    body            TEXT         NOT NULL,
    is_system       BOOLEAN      NOT NULL DEFAULT false,
    -- audit
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      UUID         REFERENCES users(id),
    modified_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    modified_by     UUID         REFERENCES users(id)
);
CREATE INDEX idx_message_templates_org ON message_templates (organization_id);

CREATE TABLE communication_messages (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID         NOT NULL REFERENCES organizations(id),
    channel         VARCHAR(20)  NOT NULL CHECK (channel IN ('email','sms')),
    recipient       VARCHAR(255) NOT NULL,
    donor_id        UUID         REFERENCES donors(id),
    template_id     UUID         REFERENCES message_templates(id),
    subject         VARCHAR(300),
    body            TEXT         NOT NULL,
    status          VARCHAR(30)  NOT NULL DEFAULT 'queued'
                        CHECK (status IN ('queued','sent','failed','skipped')),
    error_message   TEXT,
    sent_by         UUID         REFERENCES users(id),
    sent_at         TIMESTAMPTZ,
    -- audit
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      UUID         REFERENCES users(id),
    modified_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    modified_by     UUID         REFERENCES users(id)
);
CREATE INDEX idx_communication_messages_org         ON communication_messages (organization_id);
CREATE INDEX idx_communication_messages_org_created ON communication_messages (organization_id, created_at DESC);
CREATE INDEX idx_communication_messages_donor       ON communication_messages (donor_id);

-- ============================================================
-- PHASE 6 — AI & Insights
-- ============================================================

CREATE TABLE ai_insights (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID        NOT NULL REFERENCES organizations(id),
    entity_type     VARCHAR(50) NOT NULL CHECK (entity_type IN ('donor','campaign','org')),
    entity_id       UUID,
    insight         TEXT        NOT NULL,
    model           VARCHAR(100),
    generated_by    UUID        REFERENCES users(id),
    -- audit
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      UUID        REFERENCES users(id),
    modified_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by     UUID        REFERENCES users(id)
);
CREATE INDEX idx_ai_insights_entity ON ai_insights (organization_id, entity_type, entity_id);
CREATE INDEX idx_ai_insights_org    ON ai_insights (organization_id, created_at DESC);

CREATE TABLE ai_conversations (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID        NOT NULL REFERENCES organizations(id),
    user_id         UUID        NOT NULL REFERENCES users(id),
    question        TEXT        NOT NULL,
    answer          TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','answered','failed')),
    model           VARCHAR(100),
    -- audit
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      UUID        REFERENCES users(id),
    modified_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_by     UUID        REFERENCES users(id)
);
CREATE INDEX idx_ai_conversations_org  ON ai_conversations (organization_id, created_at DESC);
CREATE INDEX idx_ai_conversations_user ON ai_conversations (organization_id, user_id);

-- ============================================================
-- Operational — Audit log (append-only, no audit columns)
-- ============================================================

CREATE TABLE audit_logs (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID         REFERENCES organizations(id),
    user_id         UUID         REFERENCES users(id),
    action          VARCHAR(120) NOT NULL,
    entity_type     VARCHAR(80),
    entity_id       UUID,
    ip_address      VARCHAR(64),
    user_agent      VARCHAR(400),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_logs_org ON audit_logs (organization_id, created_at);
